services:
  mysql_auth:
    image: mysql:8.0
    container_name: mysql_auth
    environment:
      MYSQL_ROOT_PASSWORD: foodapp
      MYSQL_DATABASE: foodapp_auth
      MYSQL_USER: foodapp
      MYSQL_PASSWORD: foodapp
    ports: ["3306:3306"]
    networks:
      - foodapp_network
    volumes:
      - mysql_auth_data:/var/lib/mysql

  mysql_user:
    image: mysql:8.0
    container_name: mysql_user
    environment:
      MYSQL_ROOT_PASSWORD: foodapp
      MYSQL_DATABASE: foodapp_user
      MYSQL_USER: foodapp
      MYSQL_PASSWORD: foodapp
    ports: ["3307:3306"]
    networks:
      - foodapp_network
    volumes:
      - mysql_user_data:/var/lib/mysql

  pg_restaurant:
    image: postgis/postgis:16-3.5-alpine
    container_name: pg_restaurant
    environment:
      POSTGRES_USER: foodapp
      POSTGRES_PASSWORD: foodapp
      POSTGRES_DB: foodapp_restaurant
    ports: ["5432:5432"]
    networks:
      - foodapp_network
    volumes:
      - pg_restaurant_data:/var/lib/postgresql/data

  pg_order:
    image: postgis/postgis:16-3.5-alpine
    container_name: pg_order
    environment:
      POSTGRES_USER: foodapp
      POSTGRES_PASSWORD: foodapp
      POSTGRES_DB: foodapp_order
    ports: ["5433:5432"]
    networks:
      - foodapp_network
    volumes:
      - pg_order_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports: ["6379:6379"]
    networks:
      - foodapp_network
    volumes:
      - redis_data:/data

  nats:
    image: nats:2
    container_name: nats
    ports: ["4222:4222", "8222:8222"]
    networks:
      - foodapp_network

networks:
  foodapp_network:
    driver: bridge
volumes:
  mysql_user_data:
  mysql_auth_data:
  redis_data:
  pg_restaurant_data:
  pg_order_data:
